### PR TITLE
Fix issue with trailing zeroes not appearing for objects of type 'float'

### LINKED ISSUE #37: Trailing zeroes not appearing for objects of type 'float'
**Problem:** When generating visualizations for objects of type `float`, the images do not show the trailing zeroes.

**Current behaviour:**
Input: `[ { "name": "float", "id": 13, "value": 7.0 } ]`
Output:
image

**Expected behaviour:** it should show 7.0 as opposed to 7.

Note that this problem only occurs with trailing zeroes. Other values such as 7.123 display properly.

### PR DESCRIPTION
**Pull request by jayceelaw**
## Proposed Changes

_(Describe your changes here. Also describe the motivation for your changes: what problem do they solve, or how do they improve the application or codebase? If this pull request fixes an open issue, [use a keyword to link this pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).)_

Added trailing zero(es) to values for objects of type `float` to match Python’s float representation more closely. Fixes #37.

<details>
<summary>Screenshots of your changes (if applicable)</summary>
Before: 
After: 
</details>

## Type of Change

_(Write an `X` or a brief description next to the type or types that best describe your changes.)_

| Type                                                                                    | Applies? |
| --------------------------------------------------------------------------------------- | -------- |
| 🚨 _Breaking change_ (fix or feature that would cause existing functionality to change) |          |
| ✨ _New feature_ (non-breaking change that adds functionality)                          |          |
| 🐛 _Bug fix_ (non-breaking change that fixes an issue)                                  |  X        |
| 🎨 _User interface change_ (change to user interface; provide screenshots)              |          |
| ♻️ _Refactoring_ (internal change to codebase, without changing functionality)          |          |
| 🚦 _Test update_ (change that _only_ adds or modifies tests)                            |          |
| 📚 _Documentation update_ (change that _only_ updates documentation)                    |          |
| 📦 _Dependency update_ (change that updates a dependency)                               |          |
| 🔧 _Internal_ (change that _only_ affects developers or continuous integration)         |          |

## Checklist

_(Complete each of the following items for your pull request. Indicate that you have completed an item by changing the `[ ]` into a `[x]` in the raw text, or by clicking on the checkbox in the rendered description on GitHub.)_

Before opening your pull request:

- [x] I have performed a self-review of my changes.
    - Check that all changed files included in this pull request are intentional changes.
    - Check that all changes are relevant to the purpose of this pull request, as described above.
- [x] I have added tests for my changes, if applicable.
    - This is **required** for all bug fixes and new features.
- [x] I have updated the project documentation, if applicable.
    - This is **required** for new features.
- [x] If this is my first contribution, I have added myself to the [list of contributors](https://github.com/david-yz-liu/memory-viz/blob/master/memory-viz/package.json).
- [x] I have updated the project Changelog (this is required for all changes).

After opening your pull request:

- [x] I have verified that the CI tests have passed.
- [x] I have reviewed the test coverage changes reported by Coveralls.
- [x] I have [requested a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from a project maintainer.

## Questions and Comments

_(Include any questions or comments you have regarding your changes.)_

### CODE REVIEW

File: memory-viz/src/memory_model.ts [hunk 1]
```diff
@@ -319,6 +319,8 @@ export class MemoryModel {
             display_text = value ? "True" : "False";
         } else if (type === "str") {
             display_text = JSON.stringify(value);
+        } else if (type === "float" && typeof value === "number") {
+            display_text = value.toFixed(1);
```
Comment (david-yz-liu) [inline memory-viz/src/memory_model.ts]: This performs explicit rounding to one decimal places for all numbers. We don't want this when the user has passed in a number with decimals already (e.g., `3.14`).

BTW, this is a good test case to add, since it doesn't look like any of the existing tests caught this.

**Review by david-yz-liu — COMMENTED** [review]
@jayceelaw okay the logic looks good now, I just left one comment about the changelog entry
